# services:
#   mysql:
#     image: mysql:v1
#     container_name: mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: CrudApp@1
#     networks:
#       - spa
#     restart: always

#   backend:
#     image: backend:v1
#     container_name: backend
#     environment:
#       DB_HOST: mysql
#       DB_USER: crud
#       DB_PASSWORD: CrudApp@1
#       DB_NAME: crud_app
#     networks:
#       - spa
#     restart: always

#   react:
#     image: react:v1
#     container_name: react
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#     ports:
#       - "80:80"
#     networks:
#       - spa
#     restart: always

# networks:
#   spa:
#     driver: bridge
services:
  mysql:
    image: mysql:v1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: CrudApp@1
    networks:
      - spa
    restart: always

  redis:
    image: redis
    container_name: redis
    networks:
      - spa
    restart: always

  backend:
    image: backend:v1
    container_name: backend
    environment:
      DB_HOST: mysql
      DB_USER: crud
      DB_PASSWORD: CrudApp@1
      DB_NAME: crud_app
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - spa
    restart: always

  react:
    image: react:v1
    container_name: react
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - spa
    restart: always

networks:
  spa:
    driver: bridge